version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=express-ts
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=express-ts
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_HOST=db
